#
# travis-ci integration for udi
#

notifications:
  email: false

language: rust

os:
  - linux
  - osx

dist: trusty
sudo: false

rust:
  - 1.25.0
cache: cargo

jdk:
  - oraclejdk8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi

install:
  - export UDI_DEPS=$TRAVIS_BUILD_DIR/../deps
  - cd ..
  - git clone --depth=1 https://github.com/dxdbg/native-file-tests.git
  - cd native-file-tests/java-binding
  - mvn clean install
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 https://github.com/vmt/udis86.git && cd udis86
  - ./autogen.sh && ./configure --prefix=$UDI_DEPS && make install
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 https://github.com/PJK/libcbor.git && cd libcbor
  - cmake -DCMAKE_INSTALL_PREFIX=$UDI_DEPS . && make install
  - cd $TRAVIS_BUILD_DIR
  - cd libudirt
  - scons configure CBOR_INC=$UDI_DEPS/include CBOR_LIB=$UDI_DEPS/lib UDIS86_INC=$UDI_DEPS/include UDIS86_LIB=$UDI_DEPS/lib
  - scons all_tests
  - cd ../libudi
  - cargo test
  - cd ../libudi-c
  - cargo test
  - cd ../libudi-java
  - mvn clean verify

script: skip
