#
# SConscript for libudirt
#

import udibuild

Import('topenv')

lib_env = topenv.Clone()

lib_env.Append(CPPPATH = ['#/libudicommon', '#/libudirt'])

sources = ['udirt.c', 'udirt-malloc.c']
libs = ['udicommon']

if udibuild.IsUnix():
    sources.append('udirt-posix.c')
    sources.append('udirt-malloc-posix.c')
    sources.append('udirt-posix-pthreads.c')
    sources.append('udirt-posix-sys.c')

if udibuild.IsX86():
    sources.append('udirt-x86.c')
    libs.append('udis86')

if udibuild.IsLinux() and udibuild.IsX86():
    sources.append('udirt-linux-x86.c')

if udibuild.IsLinux():
    sources.append('udirt-posix-linux-gnu.c')
    lib_env.Append(CPPPATH = ['#/ext'])


if udibuild.IsLinux():
    libs.append('dl')

lib_env.SharedLibrary('udirt', sources, LIBS=libs,
        LIBPATH='#/build/libudicommon')
