#
# SConscript for libuditest
#

Import('topenv')

lib_env = topenv.Clone()

sources = ['libuditest.cxx']

lib_env.SharedLibrary('uditest', sources)

lib_env.StaticLibrary('uditestmain', ['uditestmain.cxx'])

# vim: ft=python
