#
# SConscript for libudi
#

import udibuild

Import('topenv')

lib_env = topenv.Clone()

lib_env.Append(CPPPATH = ['#/libudicommon', '#/libudirt'])

sources = ['libudi.c']

if udibuild.IsUnix():
    sources.append('libudi-posix.c')

libs = ['udicommon']

lib_env.SharedLibrary('udi', sources, LIBS=libs,
        LIBPATH=['#/build/libudicommon'])
