/*
 * Copyright (c) 2011-2015, UDI Contributors
 * All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package net.libudi.api.exceptions;

/**
 * The base class exception for all exceptions thrown by this library
 *
 * @author mcnulty
 */
public class UdiException extends Exception {

    /** autogenerated serial version UID */
    private static final long serialVersionUID = -1685806125753515546L;

    /**
     * Constructor.
     *
     * @param message detailed message
     */
    public UdiException(String message) {
        super(message);
    }

    /**
     * Constructor.
     *
     * @param cause the cause of the exception
     */
    public UdiException(Throwable cause) {
        super(cause);
    }

    /**
     * Constructor.
     *
     * @param message the message
     * @param cause the cause of the exception
     */
    public UdiException(String message, Throwable cause) {
        super(message, cause);
    }
}
