#
# SConscript for libudicommon
#

import udibuild

Import('topenv')

lib_env = topenv.Clone()

lib_env.Append(CPPPATH = ['#/libudirt'])

sources = ['udi-common.c']

if udibuild.IsUnix():
    sources.append('udi-common-posix.c')

if udibuild.IsLittleEndian():
    sources.append('udi-common-little.c')
else:
    sources.append('udi-common-big.c')

lib_env.StaticLibrary('udicommon', sources)
